source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/padding/YQPods.git'

use_frameworks!
platform :ios, '9.0'

target 'YQWCDBSwift_Example' do
  pod 'YQWCDBSwift', :path => '../'

  #pod 'Moya/RxSwift', '~> 12.0'
  #pod 'SnapKit', '~> 4.0.0'
  #pod 'RxCoreData', '~> 0.5.1'
  #pod 'RxDataSources', '~> 3.0'
  pod 'WCDB.swift', '1.0.8.2'
  pod 'SwiftyBeaver'
  target 'YQWCDBSwift_Tests' do
    inherit! :search_paths

    
  end
end
